Format_with_prettier = os.getenv 'FORMAT_WITH_PRETTIER' or false

require 'user.plugins'
require 'user.options'
require 'user.nvim-tree'
require 'user.cmp'
require 'user.keymaps'
require 'user.colorscheme'
require 'user.treesitter'
require 'user.comment'
require 'user.gitsigns'
require 'user.wichkey'
require 'user.focus'
require 'user.dap-install'
require 'user.mason'
require 'user.null-ls'
